name: Build

on:
  push:
      paths: ["src/**"]
  pull_request:
      paths: ["src/**"]
  workflow_dispatch:

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "alternativeticks"
      BUILD_64x: "false"
      BUILD_WINDOWS: "false"
      REALM: "sv"
